Add dn based output trigger
parthenon-hpc-lab/parthenon pull request #1210
Opened 2024-11-16 14:13 UTC by pgrete

## PR Summary

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] Change is breaking (API, behavior, ...)
  - [ ] Change is *additionally* added to CHANGELOG.md in the breaking section
  - [ ] PR is marked as breaking
  - [ ] Short summary API changes at the top of the PR (plus optionally with an automated update/fix script)
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

2024-11-16 15:13 UTC, BenWibking approved these changes, later dismissed

2024-11-16 15:14 UTC, BenWibking commented
I can't tell whether this failure is related or not:
```
The following tests FAILED:
	 68 - regression_test:boundary_exchange (Failed)
	 78 - regression_test:poisson (Failed)
```
It looks like some of the output files don't exist, so it might be.

2024-11-18 20:25 UTC, pgrete commented
> I can't tell whether the macOS CI failure is related or not:
> 
> ```
> The following tests FAILED:
> 	 68 - regression_test:boundary_exchange (Failed)
> 	 78 - regression_test:poisson (Failed)
> ```
> 
> It looks like some of the output files don't exist, so it might be.

I think the updated handling of ensuring a last time based output is written might be broken (or not behaving as before any more).
I'm investigating.

2024-11-18 21:00 UTC, Yurlungur approved these changes
Assuming we can make tests pass, LGTM. :+1: for deleting dead code.

2024-11-29 09:06 UTC, pgrete commented
The failed tests were related to a change in logic for setting `dt` and `tlim` by default as those tests did not include a temporal driver.
I now reverted that logic to the original state (i.e., `dt=0` by default, which allows for the output being triggered).
I also added changelog and doc.
If all tests pass I'm now happy to merge.

2024-11-29 15:24 UTC, BenWibking requested changes
Typo in docs. Otherwise LGTM

2024-11-29 15:24 UTC, BenWibking commented on doc/sphinx/src/outputs.rst
> +- ``dt = 100`` means that the output for the block is written every 100
I think this should be `dn = 100`.

2024-11-29 18:23 UTC, Yurlungur commented on doc/sphinx/src/outputs.rst
> +- ``dt = 100`` means that the output for the block is written every 100
I agree.

2024-11-29 18:24 UTC, Yurlungur approved these changes
Other than the minor docs typo LGTM

2024-11-29 20:39 UTC, pgrete commented on doc/sphinx/src/outputs.rst
> +- ``dt = 100`` means that the output for the block is written every 100
Done.

2024-11-29 21:41 UTC, BenWibking approved these changes

2024-11-29 23:51 UTC, merged