Update building.md for Sierra
parthenon-hpc-lab/parthenon pull request #296
Opened 2020-09-03 14:59 UTC by gshipman

## PR Summary

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md

2020-09-03 16:24 UTC, Yurlungur approved these changes

2020-09-03 19:08 UTC, AndrewGaspar requested changes

2020-09-03 19:08 UTC, AndrewGaspar commented on docs/building.md
>  # also note the `--kokkos-num-devices=6` that ensures that each process on a node uses a different GPU
```suggestion
# also note the `--kokkos-num-devices=1` that ensures that each process on a node uses a different GPU
```

2020-09-09 15:35 UTC, AndrewGaspar approved these changes

2020-09-09 15:36 UTC, merged