Close h5py files after reading
parthenon-hpc-lab/parthenon pull request #330
Opened 2020-10-22 17:44 UTC by JoshuaSBrown

## PR Summary

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md

2020-10-22 17:55 UTC, AndrewGaspar commented
I think this is more idiomatic as:
```python
        with h5py.File(goldFile,'r') as gold, h5py.File(silverFile,'r') as silver:
          varName = "/advected"
          goldData = gold[varName][:].flatten()
          silverData = gold[varName][:].flatten()
```

2020-10-22 17:58 UTC, JoshuaSBrown commented
Now that I look at the files is **silver even being used** it looks like gold is being compared with gold is this the intended use @nmsriram ?

2020-10-22 17:58 UTC, AndrewGaspar commented
oh, lol

2020-10-22 18:21 UTC, JoshuaSBrown commented
This doesn't yet fix the problem actually.

2020-10-22 18:33 UTC, Yurlungur requested changes
Good catch.

2020-10-22 18:33 UTC, Yurlungur commented on tst/regression/test_suites/restart/restart.py
> +        silver.close()
I don't think this is right. You won't be able to read the data with this. What about the following?

```python
def Analyse(self, parameters):
        # spotcheck one variable
        goldFile = 'gold.out0.00002.rhdf'
        silverFile = 'silver.out0.00002.rhdf'
        varName = "/advected"

        with h5py.File(goldFile,'r') as gold:
                goldData = gold[varName][:].flatten()

        with h5py.File(silverFile,'r') as silver:
                silverData = gold[varName][:].flatten()

        # spot check on one variable
        maxdiff = max(abs(goldData-silverData))
        print('Variable: %s, diff=%g, N=%d'%(varName,maxdiff,len(goldData)))

        return (maxdiff == 0.0)
```

This is also more pythonic. I'm pretty sure that the `with` function automatically cleans up the `gold` and `silver` h5py objects so you don't need to call `close`.

2020-10-22 18:34 UTC, Yurlungur commented
Oops. @AndrewGaspar beat me to it lol.

2020-10-22 19:21 UTC, JoshuaSBrown commented
So for some reason, the `[:]` syntax is causing problems. This works though:

```
    gold = h5py.File(goldFile,'r')
    n1 = np.zeros(gold[varName].shape, dtype=np.single)
    gold[varName].read_direct(n1)
    gold.close()
```

2020-10-22 21:31 UTC, JoshuaSBrown commented
Hey can I get approval to merge this?

2020-10-22 21:33 UTC, AndrewGaspar requested changes

2020-10-22 21:33 UTC, AndrewGaspar commented on tst/regression/test_suites/restart/restart.py
> +      gold[varName].read_direct(silverData)
let's not merge until this is fixed.
```suggestion
      silver[varName].read_direct(silverData)
```

2020-10-22 21:33 UTC, Yurlungur approved these changes
yep looks good

2020-10-22 21:34 UTC, AndrewGaspar commented on tst/regression/test_suites/restart/restart.py
> +      silverData = np.zeros(gold[varName].shape, dtype=np.single)
```suggestion
      silverData = np.zeros(silver[varName].shape, dtype=np.single)
```

2020-10-22 22:08 UTC, JoshuaSBrown commented
@AndrewGaspar

2020-10-22 22:19 UTC, AndrewGaspar commented
Did you run the test? It's not run in the acid

2020-10-22 22:44 UTC, JoshuaSBrown commented
@AndrewGaspar I didn't know that we run our tests through acid? lol I don't know how anything will survive that.

2020-10-23 09:25 UTC, pgrete requested changes
What's acid?

2020-10-23 09:25 UTC, pgrete commented on tst/regression/test_suites/restart/restart.py
> +    maxdiff = max(abs(goldData-silverData))
I'm not sure the flattening is required here. How about
```suggestion
    maxdiff = np.abs(goldData-silverData).max()
```

2020-10-23 09:25 UTC, pgrete commented on tst/regression/test_suites/restart/restart.py
> +      goldData = np.zeros(gold[varName].shape, dtype=np.single)
Our default config is double precision in Parthenon so we also write/read double precision outputs for the restart files.
Potentially, that may require lowering the diff threshold below.

```suggestion
      goldData = np.zeros(gold[varName].shape, dtype=np.float64)
```

2020-10-23 09:25 UTC, pgrete commented on tst/regression/test_suites/restart/restart.py
> +      silverData = np.zeros(silver[varName].shape, dtype=np.single)
```suggestion
      silverData = np.zeros(silver[varName].shape, dtype=np.float64)
```

2020-10-23 09:40 UTC, pgrete commented
One more comment, before anyone hits merge here please manually trigger the test suite on GitLab so that the restart tests are actually run and we don't discover that sth doesn't work first in develop.

2020-10-23 15:46 UTC, AndrewGaspar commented
Sorry, acid was supposed to be CI - I was on my phone. Apple is very aggressive with their autocorrect...

@nmsriram is currently looking at the test - it does, indeed, fail.

How do you manually trigger the CI?

2020-10-23 15:51 UTC, pgrete commented
There's a "Run pipeline" button here https://gitlab.com/pgrete/parthenon/-/pipelines (need to be logged in).
Given that this is a manual "web" trigger this includes all tests that have the "web" keyword.

2020-10-23 20:46 UTC, nmsriram approved these changes

2020-10-23 20:46 UTC, nmsriram commented on tst/regression/test_suites/restart/restart.py
> +    silverFile = 'silver.out0.00002.rhdf'
Good catch on the silver file name.

2020-10-26 22:32 UTC, AndrewGaspar approved these changes

2020-10-26 22:33 UTC, AndrewGaspar requested changes
Wait, it looks like the original change this PR made is gone now?

2020-10-26 22:35 UTC, AndrewGaspar requested changes

2020-10-26 22:35 UTC, AndrewGaspar commented on tst/regression/test_suites/restart/restart.py
> +        silverData = silver[varName][:].flatten()
"with" statement is completely gone"?

2020-10-26 22:40 UTC, JoshuaSBrown commented on tst/regression/test_suites/restart/restart.py
> +        silverData = silver[varName][:].flatten()
What the heck did I do...

2020-10-27 15:00 UTC, JoshuaSBrown commented
Waiting for this to pass https://gitlab.com/pgrete/parthenon/-/pipelines/208253354

2020-10-27 16:47 UTC, JoshuaSBrown commented
This is finally ready!

2020-10-27 22:49 UTC, JoshuaSBrown commented
@pgrete @AndrewGaspar

2020-10-27 22:51 UTC, AndrewGaspar approved these changes

2020-10-28 18:33 UTC, pgrete approved these changes

2020-10-28 18:34 UTC, merged