[WIP] Joshua s brown/refactor plm functions
parthenon-hpc-lab/parthenon pull request #341
Opened 2020-10-27 20:11 UTC by JoshuaSBrown

## PR Summary

This pr attempts to reduce the amount of redundant code in the plm source file. There was a lot of boiler plate that was refactored into smaller hopefully clearer functions. 

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md

2020-10-27 20:12 UTC, JoshuaSBrown commented
@par-hermes format

2020-10-27 20:35 UTC, JoshuaSBrown commented
Full pipeline https://gitlab.com/pgrete/parthenon/-/pipelines/208418086

2020-10-28 18:29 UTC, pgrete commented
I'm referring to @jmstone here for review as he also refactored the PLM functions.

Independently, given that this is a performance critical part of Parthenon, it'd be great to see some profiling/benchmarking results of those function on both CPUs and GPUs comparing to the original implementation.

2020-10-28 19:01 UTC, JoshuaSBrown commented
> I'm referring to @jmstone here for review as he also refactored the PLM functions.
> 
> Independently, given that this is a performance critical part of Parthenon, it'd be great to see some profiling/benchmarking results of those function on both CPUs and GPUs comparing to the original implementation.

This is a fair point.

2020-10-28 20:07 UTC, jmstone commented
This has changed a lot from the original implementation in Athena++ so I don't have much to add.  In the Kokkos version I wrote for my test code, I restricted the reconstruction to a uniform Cartesian grid and use only one function for all dimensions, so I am afraid there isn't much comparison that can be made between the two.  I agree that simplifying/refactoring these functions is a useful exercise!

2020-10-28 20:35 UTC, Yurlungur commented
Thanks for taking a shot at this. This is certainly worth rethinking. I'm looking through now.

I agree with @pgrete that some performance tests are probably very much in order.

2020-10-28 20:48 UTC, Yurlungur requested changes
Overall, I like the idea of cleaning this up to be less dimension-specific. However, I'm pretty sure we're not using this code, so I don't think it's being tested. And it will for sure die on GPU. I'm pretty sure we use the header-only version `plm_header_only.hpp` or something.

I also have a few nitpicks below.

2020-10-28 20:48 UTC, Yurlungur commented on src/reconstruct/plm.cpp
> +enum class Dimension { X1, X2, X3 };
This already exists as `X1DIR`, `X2DIR`, `X3DIR` in `defs.hpp`. I think we should use that one for this kind of thing whenever possible.

I know it's an enum there, not an enum class, but I don't like introducing new local notation. I think we should use the same notation code-wide.

2020-10-28 20:48 UTC, Yurlungur commented on src/reconstruct/plm.cpp
> +  } else {
I like having a comment here, something like
```suggestion
  } else { // if (dimmension == Dimension::X3)
```
that said, I'd rather replace `Dimension::*` with `X*DIR` for consistency.

2020-10-28 20:48 UTC, Yurlungur commented on src/reconstruct/plm.cpp
> +      data.qc(n, i) = data.q(n, k, j, i);
This is a host-side loop, but `data.q` lives on device. If compiled for GPU, this will die at runtime.

2020-10-28 20:48 UTC, Yurlungur commented on src/reconstruct/plm.cpp
> +          data.dqm(n, i) = 0.0; // ---> no concern for divide-by-0 in above line
As above, this loop is going to fail on GPU

2020-10-29 17:34 UTC, JoshuaSBrown commented
This pr is being put on hold. It looks like there is some discussion on how to treat the coordinate system which should probably be resolved before any optimizations are done here. 

E.g. whether to use a fixed grid and do transforms on top, or don't use a fixed grid etc.

@Yurlungur correct me if I'm wrong.

2020-10-29 18:22 UTC, Yurlungur commented
That seems reasonable to me. I think we could refactor `plm_inline.hpp` now, but it could be much simpler if certain conditions on the coordinate systems hold.

2021-05-18 22:58 UTC, closed without merging