Fix Darwin config use spectrum with ppc64le
parthenon-hpc-lab/parthenon pull request #443
Opened 2021-02-08 18:00 UTC by JoshuaSBrown

## PR Summary

This pr fixes the default build configuration on Darwin. Openmpi compatibility with running gpus was causing problem spectrum mpi does not appear to have the same problems. Namely the advection convergence and performance tests were failing. 

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] (@lanl.gov employees) Update copyright on changed files

2021-02-08 18:10 UTC, JoshuaSBrown commented
This should be good to go I've tested locally in my user account, but I'm still installing all the spack modules in the parthenon project space so should wait till I test them before this is merged.

2021-02-08 18:56 UTC, AndrewGaspar commented on cmake/machinecfg/Darwin.cmake
> +  else()
```suggestion
  elseif(DARWIN_MPI_PACKAGE STREQUAL "smpi")
```

2021-02-08 19:00 UTC, AndrewGaspar requested changes

2021-02-08 19:00 UTC, AndrewGaspar commented on cmake/machinecfg/Darwin.cmake
> +  if(DARWIN_MPI_PACKAGE MATCHES "openmpi")
```suggestion
  if(DARWIN_MPI_PACKAGE STREQUAL "openmpi")
```

2021-02-08 19:00 UTC, AndrewGaspar commented on cmake/TestSetup.cmake
> +    message("MPI executable ${MPIEXEC_EXECUTABLE}")
This looks spammy.

```suggestion
```

2021-02-08 21:31 UTC, JoshuaSBrown commented
@AndrewGaspar

2021-02-08 21:47 UTC, JoshuaSBrown commented
https://re-git.lanl.gov/eap-oss/parthenon/-/jobs/97386 so this shows the ci now passing on Darwin, which it hasn't been. :)

2021-02-09 16:14 UTC, JoshuaSBrown commented
@AndrewGaspar @jlippuner @Yurlungur @pgrete ping ping. :)

2021-02-09 16:18 UTC, AndrewGaspar approved these changes

2021-02-09 16:18 UTC, AndrewGaspar commented
> ping ping. :)

You should get that looked at.

2021-02-09 18:45 UTC, Yurlungur approved these changes
Thanks for fixing this.

2021-02-09 22:51 UTC, merged