Output XDMF that conforms to spec
parthenon-hpc-lab/parthenon pull request #820
Opened 2023-01-25 22:19 UTC by BenWibking

## PR Summary

This changes the XDMF output to conform to the current XDMF specification (available here: https://gitlab.kitware.com/xdmf/xdmf/blob/master/Xdmf.dtd). This allows Paraview and VisIt to open Parthenon outputs without crashing.

Fixes https://github.com/parthenon-hpc-lab/parthenon/issues/819.

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

2023-01-25 23:25 UTC, BenWibking commented
I've tested this on the outputs from the advection example with Paraview 5.11.0 and it works fine. With the same output files, VisIt 3.22 still crashes.

2023-01-26 16:02 UTC, BenWibking commented
The crashes are unrelated, and are fixed by https://github.com/parthenon-hpc-lab/parthenon/pull/796.

2023-01-26 20:42 UTC, Yurlungur approved these changes
So long as Visit's happy, I'm happy. I see some chatter on the Matrix channel, so I defer to you and @brryan about how to proceed.

2023-01-26 20:47 UTC, BenWibking commented
Visit works, but Paraview is still unhappy (emits lots of identical warnings).

2023-01-26 21:05 UTC, Yurlungur commented
Ah ok.

2023-01-27 19:04 UTC, BenWibking commented
Ok, it works for me now in both VisIt and Paraview without any warnings. @Yurlungur @brryan does this look good to you?

2023-01-27 21:23 UTC, Yurlungur approved these changes
I think this makes sense.

What output did you try this with? Before we merge I want to make sure visit/paraview are happy with both scalar and vector output and with 1 and many blocks. But assuming that's the case, I approve.

2023-01-27 21:45 UTC, BenWibking commented
I tried this with both the advection example outputs and a problem in AthenaPK. I think (?) that covers both scalar and vector output, but I didn't test a single block simulation.

2023-01-28 21:42 UTC, Yurlungur commented
> I tried this with both the advection example outputs and a problem in AthenaPK. I think (?) that covers both scalar and vector output, but I didn't test a single block simulation.

Good enough for me.

2023-02-03 13:10 UTC, pgrete requested changes
Mostly requesting cleanups. I can also confirm that the patch works (though I didn't test non-vector variables).

2023-02-03 13:10 UTC, pgrete commented on src/outputs/parthenon_hdf5.cpp
> +                                      const int &precision, bool isVector) {
Why this change?
`isVector` does not seem to be used.

2023-02-03 13:10 UTC, pgrete commented on src/outputs/parthenon_hdf5.cpp
> +      prefix + R"(<DataItem Format="HDF" Dimensions=")"; // + std::to_string(dims[0]);
```suggestion
      prefix + R"(<DataItem Format="HDF" Dimensions=")";
```

2023-02-03 13:10 UTC, pgrete commented on src/outputs/parthenon_hdf5.cpp
> -    // COUNT:  1           vector_size    nx3 nx2 nx1
I think the comment is still valid.

2023-02-03 13:10 UTC, pgrete commented on src/outputs/parthenon_hdf5.cpp
> +    }
Why this change (compared to using `dims321`)?
I think we should remain consistent, i.e., either switch to a loop everywhere and get rid of `dims321` or use `dims321` wherever possible (which should make future changes easier as all places can be identified by the same pattern)

2023-02-03 13:10 UTC, pgrete commented on src/outputs/parthenon_hdf5.cpp
> +      // dims[1] = vlen;
```suggestion
```

2023-02-03 13:10 UTC, pgrete commented on src/outputs/parthenon_hdf5.cpp
> +      // TODO(BRR) just let vinfo provide this
@brryan is that comment still valid (as `vinfo` is already used)?

2023-02-03 13:43 UTC, BenWibking commented
@brryan Can you address @pgrete's comments above? I think these changes originally came from your PR. (Alternatively, you could merge my changes into your PR.)

2023-02-03 20:35 UTC, brryan commented on src/outputs/parthenon_hdf5.cpp
> +                                      const int &precision, bool isVector) {
Yes this was a mistake, thanks for noticing this

2023-02-03 20:36 UTC, brryan commented on src/outputs/parthenon_hdf5.cpp
> -    // COUNT:  1           vector_size    nx3 nx2 nx1
:+1:

2023-02-03 20:36 UTC, brryan commented on src/outputs/parthenon_hdf5.cpp
> +    }
No reason now for this change, and in fact it was overly specialized to the 1D tensor dimension case -- reverted. I agree about `dims321` consistency.

2023-02-03 20:37 UTC, brryan commented on src/outputs/parthenon_hdf5.cpp
> +      // TODO(BRR) just let vinfo provide this
I had thought about storing `alldims` itself in `vinfo` but I don't think that's a meaningful change -- comment removed

2023-02-03 20:52 UTC, brryan commented
> @brryan Can you address @pgrete's comments above? I think these changes originally came from your PR. (Alternatively, you could merge my changes into your PR.)

Thanks for pinging me on this @BenWibking, yes I am responsible for these issues :). I made the fixes in response to @pgrete's comments in #796. While looking at this I noticed that scalar variable output wasn't working with XDMF, e.g. the `in_or_out` variable from the `calculate_pi` example (I think both `advection` and any AthenaPK problem only produce vector-type output (AthenaPK has one big state vector for all variables as I understand it)). I modified `writeXdmfSlabVariableRef` to work for the scalar case as well. Similar modifications would need to be made for 2- and 3-tensor dimension variables but since this work is already spread across two PRs and currently only I (?) use higher-tensor-dimension variables I'll open an issue instead. 

Since the changes I made weren't entirely trivial could I trouble you to merge in my latest `brryan/xdmf_fix` and check that paraview is still happy (I only checked `burgers`, `advection`, and `calculate_pi` in visit)? Then if everything works I think we can just merge this PR in.

2023-02-04 17:52 UTC, BenWibking commented
> Since the changes I made weren't entirely trivial could I trouble you to merge in my latest `brryan/xdmf_fix` and check that paraview is still happy (I only checked `burgers`, `advection`, and `calculate_pi` in visit)? Then if everything works I think we can just merge this PR in.

I've checked that `burgers`, `advection` and `calculate_pi` all load into Paraview without any issues.

2023-02-06 13:13 UTC, pgrete approved these changes

2023-02-06 13:14 UTC, pgrete commented
I removed the unused parameter, formatted the code, and added a changelog.
Enabling auto-merge now.

2023-02-06 15:10 UTC, brryan commented
> > Since the changes I made weren't entirely trivial could I trouble you to merge in my latest `brryan/xdmf_fix` and check that paraview is still happy (I only checked `burgers`, `advection`, and `calculate_pi` in visit)? Then if everything works I think we can just merge this PR in.
> 
> I've checked that `burgers`, `advection` and `calculate_pi` all load into Paraview without any issues.

Thanks @BenWibking!

> I removed the unused parameter, formatted the code, and added a changelog. Enabling auto-merge now.

Thanks @pgrete! (sorry I missed the unused parameter)

2023-02-06 18:09 UTC, Yurlungur commented
The Python/C++ formatting static check does not seem to be triggering. I tried enabling/disabling auto-merge to no effect. Is something wrong?

2023-02-06 18:10 UTC, Yurlungur commented
Looks like the format check was skipped for some reason.

2023-02-06 18:30 UTC, Yurlungur commented
I cloned the branch and ran formatting manually. It passes, so I'm going to force merge. @pgrete I think there maybe some extra step needed to get the formatting workflow to work on forks?

2023-02-06 18:30 UTC, merged